### PR TITLE
Fix automatic map vetoing

### PR DESCRIPTION
**Pull request by keenjus**
Seems like automatic map vetoing broke after faceit changed their map list rendering

### CODE REVIEW

**Comment by timche** [comment]
Thanks for fixing this! Have you tested it by any chance?

**Comment by keenjus** [comment]
Tested it only once with Chromium Edge. Seemed to work but I'd like to test it again today.

**Comment by keenjus** [comment]
Finally got to be a captain again and it worked perfectly!

**Comment by timche** [comment]
Awesome, thanks a lot dude!

**Pull request merged**
