### PR TITLE
#99 New map pool change

### PR DESCRIPTION
**Pull request by callmeashish**
Removed Cache to add Ancient into veto map pool.

### CODE REVIEW

**Comment by poacher2k** [comment]
Thank you for the PR, but this is already implemented in #82.

**Comment by Morabotti** [comment]
This is actually incorrect. #82 Only includes half of these changes. #82 Pull request added Ancient to be a possible map, but didn't include Ancient in automatic veto options.

**Comment by poacher2k** [comment]
Good catch @Morabotti !

**Comment by callmeashish** [comment]
Hey @poacher2k and @Morabotti, I have also Implemented #9 but I don't know how to test it. If you have any suggestions on how to test it, please let me know. Thanks.

**Pull request merged**
