### PR TITLE
Fix match room pick enhancements bug

### LINKED ISSUE #12: Match room show player stats broken
Ref [this reddit thread](https://www.reddit.com/r/FACEITEnhancer/comments/8liy5w/match_room_show_player_stats_picking_phase_broken/)

image

### PR DESCRIPTION
**Pull request by poacher2k**
Fixes #12

### CODE REVIEW

**Comment by timche** [comment]
Very nice! 🎉 

P.S. I have changed `ref` to `Fixes` in your description, so it closes the issue when this has been merged :)

**Comment by timche** [comment]
Also feel free and try out to release `1.4.1`.

**Comment by ntmonson** [comment]
Sorry I'm late to the party, I just got back from vacation. What do you guys think about putting the entire selector string, or if it is pretty stable and the attribute portion is less so then just the attribute portion, in a constants file? This would allow for fixes like this to be a one line change in the future. Probably not worth a refactor at any point, but something to consider when implementing these fixes in the future?

**Comment by timche** [comment]
No worries, welcome back! 

In my experience just a portion was stable if the portion was really something unique. 

I think it makes totally sense to gather the elements in a single place. Good idea!

**Comment by timche** [comment]
@ntmonson would you mind creating a ticket (issue) for that, so if we have the ressources, we can refactor that at some point.

**Pull request merged**
